dist: trusty
language: php
php:
- 5.6
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
before_script:
  - composer install
script:
  - redis-server tests/redis.conf
  - cd tests; phpunit
